export const httpStatuses = [
    {status: 100, name: "Continue"},
    {status: 101, name: "Switching Protocol"},
    {status: 102, name: "Processing"},
    {status: 103, name: "Early Hints"},
    {status: 200, name: "OK"},
    {status: 201, name: "Created"},
    {status: 202, name: "Accepted"},
    {status: 203, name: "Non-Authoritative Information"},
    {status: 204, name: "No Content"},
    {status: 205, name: "Reset Content"},
    {status: 206, name: "Partial Content"},
    {status: 300, name: "Multiple Choice"},
    {status: 301, name: "Moved Permanently"},
    {status: 302, name: "Found"},
    {status: 303, name: "See Other"},
    {status: 304, name: "Not Modified"},
    {status: 305, name: "Use Proxy"},
    {status: 306, name: "Switch Proxy"},
    {status: 307, name: "Temporary Redirect"},
    {status: 308, name: "Permanent Redirect"},
    {status: 400, name: "Bad Request"},
    {status: 401, name: "Unauthorized"},
    {status: 402, name: "Payment Required"},
    {status: 403, name: "Forbidden"},
    {status: 404, name: "Not Found"},
    {status: 405, name: "Method Not Allowed"},
    {status: 406, name: "Not Acceptable"},
    {status: 407, name: "Proxy Authentication Required"},
    {status: 408, name: "Request Timeout"},
    {status: 409, name: "Conflict"},
    {status: 410, name: "Gone"},
    {status: 411, name: "Length Required"},
    {status: 412, name: "Precondition Failed"},
    {status: 413, name: "Request Entity Too Large"},
    {status: 414, name: "Request-URI Too Long URL"},
    {status: 415, name: "Unsupported Media Type"},
    {status: 416, name: "Requested Range Not Satisfiable"},
    {status: 417, name: "Expectation Failed"},
    {status: 500, name: "Internal Server Error"},
    {status: 501, name: "Not Implemented"},
    {status: 502, name: "Bad Gateway"},
    {status: 503, name: "Service Unavailable"},
    {status: 504, name: "Gateway Timeout"},
    {status: 505, name: "HTTP Version Not Supported"},
]